##########################################################
# this has been generated from ISABELLE_HOME/etc/symbols #
##########################################################
define ->
  widget = (className, content) -> () ->
    w = document.createElement('span')
    w.className = 'substitution ' + className
    w.appendChild(document.createTextNode(content))
    return w
  symbols = 
    '\\<zero>'               : widget('special', String.fromCharCode(0x01d7ec))
    '\\<one>'                : widget('special', String.fromCharCode(0x01d7ed))
    '\\<two>'                : widget('special', String.fromCharCode(0x01d7ee))
    '\\<three>'              : widget('special', String.fromCharCode(0x01d7ef))
    '\\<four>'               : widget('special', String.fromCharCode(0x01d7f0))
    '\\<five>'               : widget('special', String.fromCharCode(0x01d7f1))
    '\\<six>'                : widget('special', String.fromCharCode(0x01d7f2))
    '\\<seven>'              : widget('special', String.fromCharCode(0x01d7f3))
    '\\<eight>'              : widget('special', String.fromCharCode(0x01d7f4))
    '\\<nine>'               : widget('special', String.fromCharCode(0x01d7f5))
    '\\<A>'                  : widget('caligraphic', 'A')
    '\\<B>'                  : widget('caligraphic', 'B')
    '\\<C>'                  : widget('caligraphic', 'C')
    '\\<D>'                  : widget('caligraphic', 'D')
    '\\<E>'                  : widget('caligraphic', 'E')
    '\\<F>'                  : widget('caligraphic', 'F')
    '\\<G>'                  : widget('caligraphic', 'G')
    '\\<H>'                  : widget('caligraphic', 'H')
    '\\<I>'                  : widget('caligraphic', 'I')
    '\\<J>'                  : widget('caligraphic', 'J')
    '\\<K>'                  : widget('caligraphic', 'K')
    '\\<L>'                  : widget('caligraphic', 'L')
    '\\<M>'                  : widget('caligraphic', 'M')
    '\\<N>'                  : widget('caligraphic', 'N')
    '\\<O>'                  : widget('caligraphic', 'O')
    '\\<P>'                  : widget('caligraphic', 'P')
    '\\<Q>'                  : widget('caligraphic', 'Q')
    '\\<R>'                  : widget('caligraphic', 'R')
    '\\<S>'                  : widget('caligraphic', 'S')
    '\\<T>'                  : widget('caligraphic', 'T')
    '\\<U>'                  : widget('caligraphic', 'U')
    '\\<V>'                  : widget('caligraphic', 'V')
    '\\<W>'                  : widget('caligraphic', 'W')
    '\\<X>'                  : widget('caligraphic', 'X')
    '\\<Y>'                  : widget('caligraphic', 'Y')
    '\\<Z>'                  : widget('caligraphic', 'Z')
    '\\<a>'                  : widget('caligraphic', 'a')
    '\\<b>'                  : widget('caligraphic', 'b')
    '\\<c>'                  : widget('caligraphic', 'c')
    '\\<d>'                  : widget('caligraphic', 'd')
    '\\<e>'                  : widget('caligraphic', 'e')
    '\\<f>'                  : widget('caligraphic', 'f')
    '\\<g>'                  : widget('caligraphic', 'g')
    '\\<h>'                  : widget('caligraphic', 'h')
    '\\<i>'                  : widget('caligraphic', 'i')
    '\\<j>'                  : widget('caligraphic', 'j')
    '\\<k>'                  : widget('caligraphic', 'k')
    '\\<l>'                  : widget('caligraphic', 'l')
    '\\<m>'                  : widget('caligraphic', 'm')
    '\\<n>'                  : widget('caligraphic', 'n')
    '\\<o>'                  : widget('caligraphic', 'o')
    '\\<p>'                  : widget('caligraphic', 'p')
    '\\<q>'                  : widget('caligraphic', 'q')
    '\\<r>'                  : widget('caligraphic', 'r')
    '\\<s>'                  : widget('caligraphic', 's')
    '\\<t>'                  : widget('caligraphic', 't')
    '\\<u>'                  : widget('caligraphic', 'u')
    '\\<v>'                  : widget('caligraphic', 'v')
    '\\<w>'                  : widget('caligraphic', 'w')
    '\\<x>'                  : widget('caligraphic', 'x')
    '\\<y>'                  : widget('caligraphic', 'y')
    '\\<z>'                  : widget('caligraphic', 'z')
    '\\<AA>'                 : widget('fraktur', 'A')
    '\\<BB>'                 : widget('fraktur', 'B')
    '\\<CC>'                 : widget('fraktur', 'C')
    '\\<DD>'                 : widget('fraktur', 'D')
    '\\<EE>'                 : widget('fraktur', 'E')
    '\\<FF>'                 : widget('fraktur', 'F')
    '\\<GG>'                 : widget('fraktur', 'G')
    '\\<HH>'                 : widget('fraktur', 'H')
    '\\<II>'                 : widget('fraktur', 'I')
    '\\<JJ>'                 : widget('fraktur', 'J')
    '\\<KK>'                 : widget('fraktur', 'K')
    '\\<LL>'                 : widget('fraktur', 'L')
    '\\<MM>'                 : widget('fraktur', 'M')
    '\\<NN>'                 : widget('fraktur', 'N')
    '\\<OO>'                 : widget('fraktur', 'O')
    '\\<PP>'                 : widget('fraktur', 'P')
    '\\<QQ>'                 : widget('fraktur', 'Q')
    '\\<RR>'                 : widget('fraktur', 'R')
    '\\<SS>'                 : widget('fraktur', 'S')
    '\\<TT>'                 : widget('fraktur', 'T')
    '\\<UU>'                 : widget('fraktur', 'U')
    '\\<VV>'                 : widget('fraktur', 'V')
    '\\<WW>'                 : widget('fraktur', 'W')
    '\\<XX>'                 : widget('fraktur', 'X')
    '\\<YY>'                 : widget('fraktur', 'Y')
    '\\<ZZ>'                 : widget('fraktur', 'Z')
    '\\<aa>'                 : widget('fraktur', 'a')
    '\\<bb>'                 : widget('fraktur', 'b')
    '\\<cc>'                 : widget('fraktur', 'c')
    '\\<dd>'                 : widget('fraktur', 'd')
    '\\<ee>'                 : widget('fraktur', 'e')
    '\\<ff>'                 : widget('fraktur', 'f')
    '\\<gg>'                 : widget('fraktur', 'g')
    '\\<hh>'                 : widget('fraktur', 'h')
    '\\<ii>'                 : widget('fraktur', 'i')
    '\\<jj>'                 : widget('fraktur', 'j')
    '\\<kk>'                 : widget('fraktur', 'k')
    '\\<ll>'                 : widget('fraktur', 'l')
    '\\<mm>'                 : widget('fraktur', 'm')
    '\\<nn>'                 : widget('fraktur', 'n')
    '\\<oo>'                 : widget('fraktur', 'o')
    '\\<pp>'                 : widget('fraktur', 'p')
    '\\<qq>'                 : widget('fraktur', 'q')
    '\\<rr>'                 : widget('fraktur', 'r')
    '\\<ss>'                 : widget('fraktur', 's')
    '\\<tt>'                 : widget('fraktur', 't')
    '\\<uu>'                 : widget('fraktur', 'u')
    '\\<vv>'                 : widget('fraktur', 'v')
    '\\<ww>'                 : widget('fraktur', 'w')
    '\\<xx>'                 : widget('fraktur', 'x')
    '\\<yy>'                 : widget('fraktur', 'y')
    '\\<zz>'                 : widget('fraktur', 'z')
    '\\<alpha>'              : widget('special', String.fromCharCode(0x0003b1))
    '\\<beta>'               : widget('special', String.fromCharCode(0x0003b2))
    '\\<gamma>'              : widget('special', String.fromCharCode(0x0003b3))
    '\\<delta>'              : widget('special', String.fromCharCode(0x0003b4))
    '\\<epsilon>'            : widget('special', String.fromCharCode(0x0003b5))
    '\\<zeta>'               : widget('special', String.fromCharCode(0x0003b6))
    '\\<eta>'                : widget('special', String.fromCharCode(0x0003b7))
    '\\<theta>'              : widget('special', String.fromCharCode(0x0003b8))
    '\\<iota>'               : widget('special', String.fromCharCode(0x0003b9))
    '\\<kappa>'              : widget('special', String.fromCharCode(0x0003ba))
    '\\<lambda>'             : widget('special', String.fromCharCode(0x0003bb))
    '\\<mu>'                 : widget('special', String.fromCharCode(0x0003bc))
    '\\<nu>'                 : widget('special', String.fromCharCode(0x0003bd))
    '\\<xi>'                 : widget('special', String.fromCharCode(0x0003be))
    '\\<pi>'                 : widget('special', String.fromCharCode(0x0003c0))
    '\\<rho>'                : widget('special', String.fromCharCode(0x0003c1))
    '\\<sigma>'              : widget('special', String.fromCharCode(0x0003c3))
    '\\<tau>'                : widget('special', String.fromCharCode(0x0003c4))
    '\\<upsilon>'            : widget('special', String.fromCharCode(0x0003c5))
    '\\<phi>'                : widget('special', String.fromCharCode(0x0003c6))
    '\\<chi>'                : widget('special', String.fromCharCode(0x0003c7))
    '\\<psi>'                : widget('special', String.fromCharCode(0x0003c8))
    '\\<omega>'              : widget('special', String.fromCharCode(0x0003c9))
    '\\<Gamma>'              : widget('special', String.fromCharCode(0x000393))
    '\\<Delta>'              : widget('special', String.fromCharCode(0x000394))
    '\\<Theta>'              : widget('special', String.fromCharCode(0x000398))
    '\\<Lambda>'             : widget('special', String.fromCharCode(0x00039b))
    '\\<Xi>'                 : widget('special', String.fromCharCode(0x00039e))
    '\\<Pi>'                 : widget('special', String.fromCharCode(0x0003a0))
    '\\<Sigma>'              : widget('special', String.fromCharCode(0x0003a3))
    '\\<Upsilon>'            : widget('special', String.fromCharCode(0x0003a5))
    '\\<Phi>'                : widget('special', String.fromCharCode(0x0003a6))
    '\\<Psi>'                : widget('special', String.fromCharCode(0x0003a8))
    '\\<Omega>'              : widget('special', String.fromCharCode(0x0003a9))
    '\\<bool>'               : widget('special', String.fromCharCode(0x01d539))
    '\\<complex>'            : widget('special', String.fromCharCode(0x002102))
    '\\<nat>'                : widget('special', String.fromCharCode(0x002115))
    '\\<rat>'                : widget('special', String.fromCharCode(0x00211a))
    '\\<real>'               : widget('special', String.fromCharCode(0x00211d))
    '\\<int>'                : widget('special', String.fromCharCode(0x002124))
    '\\<leftarrow>'          : widget('special', String.fromCharCode(0x002190))
    '\\<longleftarrow>'      : widget('special', String.fromCharCode(0x0027f5))
    '\\<rightarrow>'         : widget('special', String.fromCharCode(0x002192))
    '\\<longrightarrow>'     : widget('special', String.fromCharCode(0x0027f6))
    '\\<Leftarrow>'          : widget('special', String.fromCharCode(0x0021d0))
    '\\<Longleftarrow>'      : widget('special', String.fromCharCode(0x0027f8))
    '\\<Rightarrow>'         : widget('special', String.fromCharCode(0x0021d2))
    '\\<Longrightarrow>'     : widget('special', String.fromCharCode(0x0027f9))
    '\\<leftrightarrow>'     : widget('special', String.fromCharCode(0x002194))
    '\\<longleftrightarrow>' : widget('special', String.fromCharCode(0x0027f7))
    '\\<Leftrightarrow>'     : widget('special', String.fromCharCode(0x0021d4))
    '\\<Longleftrightarrow>' : widget('special', String.fromCharCode(0x0027fa))
    '\\<mapsto>'             : widget('special', String.fromCharCode(0x0021a6))
    '\\<longmapsto>'         : widget('special', String.fromCharCode(0x0027fc))
    '\\<midarrow>'           : widget('special', String.fromCharCode(0x002500))
    '\\<Midarrow>'           : widget('special', String.fromCharCode(0x002550))
    '\\<hookleftarrow>'      : widget('special', String.fromCharCode(0x0021a9))
    '\\<hookrightarrow>'     : widget('special', String.fromCharCode(0x0021aa))
    '\\<leftharpoondown>'    : widget('special', String.fromCharCode(0x0021bd))
    '\\<rightharpoondown>'   : widget('special', String.fromCharCode(0x0021c1))
    '\\<leftharpoonup>'      : widget('special', String.fromCharCode(0x0021bc))
    '\\<rightharpoonup>'     : widget('special', String.fromCharCode(0x0021c0))
    '\\<rightleftharpoons>'  : widget('special', String.fromCharCode(0x0021cc))
    '\\<leadsto>'            : widget('special', String.fromCharCode(0x00219d))
    '\\<downharpoonleft>'    : widget('special', String.fromCharCode(0x0021c3))
    '\\<downharpoonright>'   : widget('special', String.fromCharCode(0x0021c2))
    '\\<upharpoonleft>'      : widget('special', String.fromCharCode(0x0021bf))
    '\\<upharpoonright>'     : widget('special', String.fromCharCode(0x0021be))
    '\\<restriction>'        : widget('special', String.fromCharCode(0x0021be))
    '\\<Colon>'              : widget('special', String.fromCharCode(0x002237))
    '\\<up>'                 : widget('special', String.fromCharCode(0x002191))
    '\\<Up>'                 : widget('special', String.fromCharCode(0x0021d1))
    '\\<down>'               : widget('special', String.fromCharCode(0x002193))
    '\\<Down>'               : widget('special', String.fromCharCode(0x0021d3))
    '\\<updown>'             : widget('special', String.fromCharCode(0x002195))
    '\\<Updown>'             : widget('special', String.fromCharCode(0x0021d5))
    '\\<langle>'             : widget('special', String.fromCharCode(0x0027e8))
    '\\<rangle>'             : widget('special', String.fromCharCode(0x0027e9))
    '\\<lceil>'              : widget('special', String.fromCharCode(0x002308))
    '\\<rceil>'              : widget('special', String.fromCharCode(0x002309))
    '\\<lfloor>'             : widget('special', String.fromCharCode(0x00230a))
    '\\<rfloor>'             : widget('special', String.fromCharCode(0x00230b))
    '\\<lparr>'              : widget('special', String.fromCharCode(0x002987))
    '\\<rparr>'              : widget('special', String.fromCharCode(0x002988))
    '\\<lbrakk>'             : widget('special', String.fromCharCode(0x0027e6))
    '\\<rbrakk>'             : widget('special', String.fromCharCode(0x0027e7))
    '\\<lbrace>'             : widget('special', String.fromCharCode(0x002983))
    '\\<rbrace>'             : widget('special', String.fromCharCode(0x002984))
    '\\<guillemotleft>'      : widget('special', String.fromCharCode(0x0000ab))
    '\\<guillemotright>'     : widget('special', String.fromCharCode(0x0000bb))
    '\\<bottom>'             : widget('special', String.fromCharCode(0x0022a5))
    '\\<top>'                : widget('special', String.fromCharCode(0x0022a4))
    '\\<and>'                : widget('special', String.fromCharCode(0x002227))
    '\\<And>'                : widget('special', String.fromCharCode(0x0022c0))
    '\\<or>'                 : widget('special', String.fromCharCode(0x002228))
    '\\<Or>'                 : widget('special', String.fromCharCode(0x0022c1))
    '\\<forall>'             : widget('special', String.fromCharCode(0x002200))
    '\\<exists>'             : widget('special', String.fromCharCode(0x002203))
    '\\<nexists>'            : widget('special', String.fromCharCode(0x002204))
    '\\<not>'                : widget('special', String.fromCharCode(0x0000ac))
    '\\<box>'                : widget('special', String.fromCharCode(0x0025a1))
    '\\<diamond>'            : widget('special', String.fromCharCode(0x0025c7))
    '\\<turnstile>'          : widget('special', String.fromCharCode(0x0022a2))
    '\\<Turnstile>'          : widget('special', String.fromCharCode(0x0022a8))
    '\\<tturnstile>'         : widget('special', String.fromCharCode(0x0022a9))
    '\\<TTurnstile>'         : widget('special', String.fromCharCode(0x0022ab))
    '\\<stileturn>'          : widget('special', String.fromCharCode(0x0022a3))
    '\\<surd>'               : widget('special', String.fromCharCode(0x00221a))
    '\\<le>'                 : widget('special', String.fromCharCode(0x002264))
    '\\<ge>'                 : widget('special', String.fromCharCode(0x002265))
    '\\<lless>'              : widget('special', String.fromCharCode(0x00226a))
    '\\<ggreater>'           : widget('special', String.fromCharCode(0x00226b))
    '\\<lesssim>'            : widget('special', String.fromCharCode(0x002272))
    '\\<greatersim>'         : widget('special', String.fromCharCode(0x002273))
    '\\<lessapprox>'         : widget('special', String.fromCharCode(0x002a85))
    '\\<greaterapprox>'      : widget('special', String.fromCharCode(0x002a86))
    '\\<in>'                 : widget('special', String.fromCharCode(0x002208))
    '\\<notin>'              : widget('special', String.fromCharCode(0x002209))
    '\\<subset>'             : widget('special', String.fromCharCode(0x002282))
    '\\<supset>'             : widget('special', String.fromCharCode(0x002283))
    '\\<subseteq>'           : widget('special', String.fromCharCode(0x002286))
    '\\<supseteq>'           : widget('special', String.fromCharCode(0x002287))
    '\\<sqsubset>'           : widget('special', String.fromCharCode(0x00228f))
    '\\<sqsupset>'           : widget('special', String.fromCharCode(0x002290))
    '\\<sqsubseteq>'         : widget('special', String.fromCharCode(0x002291))
    '\\<sqsupseteq>'         : widget('special', String.fromCharCode(0x002292))
    '\\<inter>'              : widget('special', String.fromCharCode(0x002229))
    '\\<Inter>'              : widget('special', String.fromCharCode(0x0022c2))
    '\\<union>'              : widget('special', String.fromCharCode(0x00222a))
    '\\<Union>'              : widget('special', String.fromCharCode(0x0022c3))
    '\\<squnion>'            : widget('special', String.fromCharCode(0x002294))
    '\\<Squnion>'            : widget('special', String.fromCharCode(0x002a06))
    '\\<sqinter>'            : widget('special', String.fromCharCode(0x002293))
    '\\<Sqinter>'            : widget('special', String.fromCharCode(0x002a05))
    '\\<setminus>'           : widget('special', String.fromCharCode(0x002216))
    '\\<propto>'             : widget('special', String.fromCharCode(0x00221d))
    '\\<uplus>'              : widget('special', String.fromCharCode(0x00228e))
    '\\<Uplus>'              : widget('special', String.fromCharCode(0x002a04))
    '\\<noteq>'              : widget('special', String.fromCharCode(0x002260))
    '\\<sim>'                : widget('special', String.fromCharCode(0x00223c))
    '\\<doteq>'              : widget('special', String.fromCharCode(0x002250))
    '\\<simeq>'              : widget('special', String.fromCharCode(0x002243))
    '\\<approx>'             : widget('special', String.fromCharCode(0x002248))
    '\\<asymp>'              : widget('special', String.fromCharCode(0x00224d))
    '\\<cong>'               : widget('special', String.fromCharCode(0x002245))
    '\\<smile>'              : widget('special', String.fromCharCode(0x002323))
    '\\<equiv>'              : widget('special', String.fromCharCode(0x002261))
    '\\<frown>'              : widget('special', String.fromCharCode(0x002322))
    '\\<Join>'               : widget('special', String.fromCharCode(0x0022c8))
    '\\<bowtie>'             : widget('special', String.fromCharCode(0x002a1d))
    '\\<prec>'               : widget('special', String.fromCharCode(0x00227a))
    '\\<succ>'               : widget('special', String.fromCharCode(0x00227b))
    '\\<preceq>'             : widget('special', String.fromCharCode(0x00227c))
    '\\<succeq>'             : widget('special', String.fromCharCode(0x00227d))
    '\\<parallel>'           : widget('special', String.fromCharCode(0x002225))
    '\\<bar>'                : widget('special', String.fromCharCode(0x0000a6))
    '\\<plusminus>'          : widget('special', String.fromCharCode(0x0000b1))
    '\\<minusplus>'          : widget('special', String.fromCharCode(0x002213))
    '\\<times>'              : widget('special', String.fromCharCode(0x0000d7))
    '\\<div>'                : widget('special', String.fromCharCode(0x0000f7))
    '\\<cdot>'               : widget('special', String.fromCharCode(0x0022c5))
    '\\<star>'               : widget('special', String.fromCharCode(0x0022c6))
    '\\<bullet>'             : widget('special', String.fromCharCode(0x002219))
    '\\<circ>'               : widget('special', String.fromCharCode(0x002218))
    '\\<dagger>'             : widget('special', String.fromCharCode(0x002020))
    '\\<ddagger>'            : widget('special', String.fromCharCode(0x002021))
    '\\<lhd>'                : widget('special', String.fromCharCode(0x0022b2))
    '\\<rhd>'                : widget('special', String.fromCharCode(0x0022b3))
    '\\<unlhd>'              : widget('special', String.fromCharCode(0x0022b4))
    '\\<unrhd>'              : widget('special', String.fromCharCode(0x0022b5))
    '\\<triangleleft>'       : widget('special', String.fromCharCode(0x0025c3))
    '\\<triangleright>'      : widget('special', String.fromCharCode(0x0025b9))
    '\\<triangle>'           : widget('special', String.fromCharCode(0x0025b3))
    '\\<triangleq>'          : widget('special', String.fromCharCode(0x00225c))
    '\\<oplus>'              : widget('special', String.fromCharCode(0x002295))
    '\\<Oplus>'              : widget('special', String.fromCharCode(0x002a01))
    '\\<otimes>'             : widget('special', String.fromCharCode(0x002297))
    '\\<Otimes>'             : widget('special', String.fromCharCode(0x002a02))
    '\\<odot>'               : widget('special', String.fromCharCode(0x002299))
    '\\<Odot>'               : widget('special', String.fromCharCode(0x002a00))
    '\\<ominus>'             : widget('special', String.fromCharCode(0x002296))
    '\\<oslash>'             : widget('special', String.fromCharCode(0x002298))
    '\\<dots>'               : widget('special', String.fromCharCode(0x002026))
    '\\<cdots>'              : widget('special', String.fromCharCode(0x0022ef))
    '\\<Sum>'                : widget('special', String.fromCharCode(0x002211))
    '\\<Prod>'               : widget('special', String.fromCharCode(0x00220f))
    '\\<Coprod>'             : widget('special', String.fromCharCode(0x002210))
    '\\<infinity>'           : widget('special', String.fromCharCode(0x00221e))
    '\\<integral>'           : widget('special', String.fromCharCode(0x00222b))
    '\\<ointegral>'          : widget('special', String.fromCharCode(0x00222e))
    '\\<clubsuit>'           : widget('special', String.fromCharCode(0x002663))
    '\\<diamondsuit>'        : widget('special', String.fromCharCode(0x002662))
    '\\<heartsuit>'          : widget('special', String.fromCharCode(0x002661))
    '\\<spadesuit>'          : widget('special', String.fromCharCode(0x002660))
    '\\<aleph>'              : widget('special', String.fromCharCode(0x002135))
    '\\<emptyset>'           : widget('special', String.fromCharCode(0x002205))
    '\\<nabla>'              : widget('special', String.fromCharCode(0x002207))
    '\\<partial>'            : widget('special', String.fromCharCode(0x002202))
    '\\<Re>'                 : widget('special', String.fromCharCode(0x00211c))
    '\\<Im>'                 : widget('special', String.fromCharCode(0x002111))
    '\\<flat>'               : widget('special', String.fromCharCode(0x00266d))
    '\\<natural>'            : widget('special', String.fromCharCode(0x00266e))
    '\\<sharp>'              : widget('special', String.fromCharCode(0x00266f))
    '\\<angle>'              : widget('special', String.fromCharCode(0x002220))
    '\\<copyright>'          : widget('special', String.fromCharCode(0x0000a9))
    '\\<registered>'         : widget('special', String.fromCharCode(0x0000ae))
    '\\<hyphen>'             : widget('special', String.fromCharCode(0x0000ad))
    '\\<inverse>'            : widget('special', String.fromCharCode(0x0000af))
    '\\<onesuperior>'        : widget('special', String.fromCharCode(0x0000b9))
    '\\<onequarter>'         : widget('special', String.fromCharCode(0x0000bc))
    '\\<twosuperior>'        : widget('special', String.fromCharCode(0x0000b2))
    '\\<onehalf>'            : widget('special', String.fromCharCode(0x0000bd))
    '\\<threesuperior>'      : widget('special', String.fromCharCode(0x0000b3))
    '\\<threequarters>'      : widget('special', String.fromCharCode(0x0000be))
    '\\<ordfeminine>'        : widget('special', String.fromCharCode(0x0000aa))
    '\\<ordmasculine>'       : widget('special', String.fromCharCode(0x0000ba))
    '\\<section>'            : widget('special', String.fromCharCode(0x0000a7))
    '\\<paragraph>'          : widget('special', String.fromCharCode(0x0000b6))
    '\\<exclamdown>'         : widget('special', String.fromCharCode(0x0000a1))
    '\\<questiondown>'       : widget('special', String.fromCharCode(0x0000bf))
    '\\<euro>'               : widget('special', String.fromCharCode(0x0020ac))
    '\\<pounds>'             : widget('special', String.fromCharCode(0x0000a3))
    '\\<yen>'                : widget('special', String.fromCharCode(0x0000a5))
    '\\<cent>'               : widget('special', String.fromCharCode(0x0000a2))
    '\\<currency>'           : widget('special', String.fromCharCode(0x0000a4))
    '\\<degree>'             : widget('special', String.fromCharCode(0x0000b0))
    '\\<amalg>'              : widget('special', String.fromCharCode(0x002a3f))
    '\\<mho>'                : widget('special', String.fromCharCode(0x002127))
    '\\<lozenge>'            : widget('special', String.fromCharCode(0x0025ca))
    '\\<wp>'                 : widget('special', String.fromCharCode(0x002118))
    '\\<wrong>'              : widget('special', String.fromCharCode(0x002240))
    '\\<struct>'             : widget('special', String.fromCharCode(0x0022c4))
    '\\<acute>'              : widget('special', String.fromCharCode(0x0000b4))
    '\\<index>'              : widget('special', String.fromCharCode(0x000131))
    '\\<dieresis>'           : widget('special', String.fromCharCode(0x0000a8))
    '\\<cedilla>'            : widget('special', String.fromCharCode(0x0000b8))
    '\\<hungarumlaut>'       : widget('special', String.fromCharCode(0x0002dd))
    '\\<some>'               : widget('special', String.fromCharCode(0x0003f5))

    '%'                      : widget('special', String.fromCharCode(0x0003bb))
    '->'                     : widget('special', String.fromCharCode(0x002192)  )
    '-->'                    : widget('special', String.fromCharCode(0x0027f6)  )
    '=>'                     : widget('special', String.fromCharCode(0x0021d2)  )
    '==>'                    : widget('special', String.fromCharCode(0x0027f9)  )
    '<->'                    : widget('special', String.fromCharCode(0x0027f7)  )
    '<=>'                    : widget('special', String.fromCharCode(0x0027fa)  )
    '|->'                    : widget('special', String.fromCharCode(0x0021a6)  )
    '|-->'                   : widget('special', String.fromCharCode(0x0027fc)  )
    '~>'                     : widget('special', String.fromCharCode(0x00219d)  )
    '<.'                     : widget('special', String.fromCharCode(0x0027e8)  )
    '.>'                     : widget('special', String.fromCharCode(0x0027e9)  )
    '(|'                     : widget('special', String.fromCharCode(0x002987)  )
    '|)'                     : widget('special', String.fromCharCode(0x002988)  )
    '[|'                     : widget('special', String.fromCharCode(0x0027e6)  )
    '|]'                     : widget('special', String.fromCharCode(0x0027e7)  )
    '{.'                     : widget('special', String.fromCharCode(0x002983)  )
    '.}'                     : widget('special', String.fromCharCode(0x002984)  )
    '<<'                     : widget('special', String.fromCharCode(0x0000ab)  )
    '>>'                     : widget('special', String.fromCharCode(0x0000bb)  )
    '/\\'                    : widget('special', String.fromCharCode(0x002227)  )
    '!!'                     : widget('special', String.fromCharCode(0x0022c0)  )
    '\\/'                    : widget('special', String.fromCharCode(0x002228)  )
    '??'                     : widget('special', String.fromCharCode(0x0022c1)  )
    '!'                      : widget('special', String.fromCharCode(0x002200)  )
    '?'                      : widget('special', String.fromCharCode(0x002203)  )
    '~?'                     : widget('special', String.fromCharCode(0x002204)  )
    '~'                      : widget('special', String.fromCharCode(0x0000ac)  )
    '|-'                     : widget('special', String.fromCharCode(0x0022a2)  )
    '|='                     : widget('special', String.fromCharCode(0x0022a8)  )
    '||-'                    : widget('special', String.fromCharCode(0x0022a9)  )
    '||='                    : widget('special', String.fromCharCode(0x0022ab)  )
    '-|'                     : widget('special', String.fromCharCode(0x0022a3)  )
    '<='                     : widget('special', String.fromCharCode(0x002264)  )
    '>='                     : widget('special', String.fromCharCode(0x002265)  )
    ':'                      : widget('special', String.fromCharCode(0x002208)  )
    '~:'                     : widget('special', String.fromCharCode(0x002209)  )
    '(='                     : widget('special', String.fromCharCode(0x002286)  )
    '=)'                     : widget('special', String.fromCharCode(0x002287)  )
    '[='                     : widget('special', String.fromCharCode(0x002291)  )
    '=]'                     : widget('special', String.fromCharCode(0x002292)  )
    '~='                     : widget('special', String.fromCharCode(0x002260)  )
    '=='                     : widget('special', String.fromCharCode(0x002261)  )
    '||'                     : widget('special', String.fromCharCode(0x002225)  )
    '+o'                     : widget('special', String.fromCharCode(0x002295)  )
    '+O'                     : widget('special', String.fromCharCode(0x002a01)  )
    '*o'                     : widget('special', String.fromCharCode(0x002297)  )
    '*O'                     : widget('special', String.fromCharCode(0x002a02)  )
    '.o'                     : widget('special', String.fromCharCode(0x002299)  )
    '.O'                     : widget('special', String.fromCharCode(0x002a00)  )
    '-o'                     : widget('special', String.fromCharCode(0x002296)  )
    '/o'                     : widget('special', String.fromCharCode(0x002298)    )
    '=_'                     : widget('special', String.fromCharCode(0x0021e9)  )
    '=^'                     : widget('special', String.fromCharCode(0x0021e7)  )
    '-_'                     : widget('special', String.fromCharCode(0x0021e3)  )
    '-^'                     : widget('special', String.fromCharCode(0x0021e1)  )
    '=_('                    : widget('special', String.fromCharCode(0x0021d8)  )
    '=_)'                    : widget('special', String.fromCharCode(0x0021d9)  )
    '=^('                    : widget('special', String.fromCharCode(0x0021d7)  )
    '=^)'                    : widget('special', String.fromCharCode(0x0021d6)  )
    '-.'                     : widget('special', String.fromCharCode(0x002759))
    '...'                    : widget('special', String.fromCharCode(0x002026))
    'Int'                    : widget('special', String.fromCharCode(0x002229)  )
    'Inter'                  : widget('special', String.fromCharCode(0x0022c2)  )
    'Un'                     : widget('special', String.fromCharCode(0x00222a)  )
    'Union'                  : widget('special', String.fromCharCode(0x0022c3)  )
    'SUM'                    : widget('special', String.fromCharCode(0x002211)  )
    'PROD'                   : widget('special', String.fromCharCode(0x00220f))
  return symbols